#!/bin/bash

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
PROJECT_DIR=$(dirname "$SCRIPT_DIR")
BACK_END_DIR="$PROJECT_DIR/backend"

cd $BACK_END_DIR
if [ ! -d "venv" ]; then
    pip cache purge
    virtualenv venv
fi
source venv/bin/activate
fastapi dev app/main.py